set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_LINKER_SUBSYSTEM Console)
set(VCPKG_LINKER_SUBSYSTEM_MIN_VERSION 5.01)

set(VCPKG_CXX_FLAGS /Zc:threadSafeInit-)
set(VCPKG_C_FLAGS /Zc:threadSafeInit-)